# -*- coding: utf-8 -*-
"""Copy of app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfSLlTYFqit4EP7ByAmgXp02JUQgR9WF
"""

!pip install streamlit

import streamlit as st
import joblib
import numpy as np
import random

st.set_page_config(page_title="Movie Popularity Predictor", page_icon="🎬", layout="centered")

@st.cache_resource
def load_models():
    try:
        model = joblib.load('best_model.pkl')
        cv = joblib.load('vectorizer.pkl')
        scaler = joblib.load('scaler.pkl')
        return model, cv, scaler
    except Exception as e:
        st.error(f"Error loading model files: {e}")
        return None, None, None

model, cv, scaler = load_models()

sample_movies = {
    "The Shawshank Redemption": ("The Shawshank Redemption", "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", 1994, 9, 23, 9.3, 24000),
    "The Godfather": ("The Godfather", "A powerful mafia family story of love, loyalty and betrayal.", 1972, 3, 24, 9.2, 18000),
    "Inception": ("Inception", "A thief enters people's dreams to steal secrets from their subconscious.", 2010, 7, 16, 8.8, 35000),
    "The Dark Knight": ("The Dark Knight", "Batman faces the Joker who creates chaos in Gotham City.", 2008, 7, 18, 9.0, 30000),
    "Interstellar": ("Interstellar", "A team of explorers travel through a wormhole in space.", 2014, 11, 7, 8.6, 32000),
    "Parasite": ("Parasite", "A poor family schemes to become employed by a wealthy family.", 2019, 5, 30, 8.5, 15000),
    "The Lion King": ("The Lion King", "A young lion prince flees his kingdom after his father is murdered.", 1994, 6, 24, 8.5, 14000),
}

st.title("🎬 Movie Popularity Predictor")
st.write("Predict whether a movie will have **Low, Medium or High** popularity!")
st.divider()

if 'selected_movie' not in st.session_state:
    st.session_state.selected_movie = "The Shawshank Redemption"

if st.button("🎲 Surprise Me — Random Movie", use_container_width=True):
    st.session_state.selected_movie = random.choice(list(sample_movies.keys()))
    st.rerun()

selected = st.selectbox(
    "🎬 Or Select a Movie:",
    list(sample_movies.keys()),
    index=list(sample_movies.keys()).index(st.session_state.selected_movie)
)
st.session_state.selected_movie = selected
movie_data = sample_movies[st.session_state.selected_movie]

st.divider()

movie_title = st.text_input("Movie Title", value=movie_data[0])
movie_overview = st.text_area("Overview", value=movie_data[1])

col1, col2 = st.columns(2)

with col1:
    vote_average = st.number_input("Vote Average", min_value=0.0, max_value=10.0, value=float(movie_data[5]), step=0.1)
    vote_count = st.number_input("Vote Count", min_value=0, max_value=50000, value=int(movie_data[6]), step=10)
    release_year = st.number_input("Release Year", min_value=1900, max_value=2026, value=int(movie_data[2]))

with col2:
    months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
    release_month = st.slider("Release Month", min_value=1, max_value=12, value=int(movie_data[3]))
    st.write(f"**{months[release_month-1]}**")
    release_day = st.slider("Release Day", min_value=1, max_value=31, value=int(movie_data[4]))

st.divider()

if st.button("🔮 Predict Popularity", type="primary", use_container_width=True):
    if model is not None:
        try:
            scaled = scaler.transform([[vote_average, vote_count, 0]])
            vote_average_scaled = scaled[0][0]
            vote_count_scaled = scaled[0][1]

            overview_cv = cv.transform([movie_overview]).toarray()

            numeric_features = np.array([[vote_average_scaled, vote_count_scaled,
                                          release_year, release_month, release_day]])
            input_data = np.concatenate([numeric_features, overview_cv], axis=1)

            prediction = model.predict(input_data)[0]

            st.divider()
            st.subheader("🎯 Prediction Results")

            if prediction == 0:
                st.success("🟢 Low Popularity")
                st.write(f"📉 **{movie_title}** is predicted to have **Low** popularity.")
            elif prediction == 1:
                st.warning("🟡 Medium Popularity")
                st.write(f"👍 **{movie_title}** is predicted to have **Medium** popularity.")
            else:
                st.error("🔴 High Popularity")
                st.balloons()
                st.write(f"🌟 **{movie_title}** is predicted to have **High** popularity!")

        except Exception as e:
            st.error(f"Prediction failed: {e}")